#!/bin/bash

NAME=swarmesb
RUN_AS_USER=swarm

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/bin
NODE_PATH="/opt/node_modules"
SWARM_PATH="/opt/channelsESB"
SWARM_NODETYPE="release"
export SWARM_PATH
export NODE_PATH
export SWARM_NODETYPE
DAEMON=/usr/bin/node

LAUNCHER_ARGS=$SWARM_PATH/adapters/Launcher.js
LAUNCHER_NAME=$NAME-launcher
LAUNCHER_DESC=$NAME-launcher
LAUNCHER_PIDFILE=/var/run/$LAUNCHER_NAME

set -e

cd $SWARM_PATH

case "$1" in
  start)
        echo -n "Starting Swarms... "
        echo export SWARM_PATH=$SWARM_PATH;export NODE_PATH=$NODE_PATH;export SWARM_NODETYPE=$SWARM_NODETYPE; nohup $DAEMON $LAUNCHER_ARGS >$SWARM_PATH/consoleLog&
        su - $RUN_AS_USER -c "export SWARM_PATH=$SWARM_PATH;export NODE_PATH=$NODE_PATH;export SWARM_NODETYPE= $SWARM_NODETYPE; nohup $DAEMON $LAUNCHER_ARGS >$SWARM_PATH/consoleLog&"
        ;;
  stop)
        echo -n "Stopping Swarms"
        killall node
        ;;
      *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop}" >&2
        exit 1
        ;;
esac

exit 0

